# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS sentry_crashpad::compat sentry_crashpad::minidump sentry_crashpad::snapshot sentry_crashpad::util sentry_crashpad::mini_chromium sentry_crashpad::client sentry_crashpad::zlib sentry_crashpad::tools sentry_crashpad::handler sentry_crashpad::crashpad_handler)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target sentry_crashpad::compat
add_library(sentry_crashpad::compat INTERFACE IMPORTED)

# Create imported target sentry_crashpad::minidump
add_library(sentry_crashpad::minidump STATIC IMPORTED)

set_target_properties(sentry_crashpad::minidump PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>;sentry_crashpad::compat;sentry_crashpad::snapshot;sentry_crashpad::util;sentry_crashpad::mini_chromium"
)

# Create imported target sentry_crashpad::snapshot
add_library(sentry_crashpad::snapshot STATIC IMPORTED)

set_target_properties(sentry_crashpad::snapshot PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>;sentry_crashpad::client;sentry_crashpad::compat;sentry_crashpad::util;sentry_crashpad::mini_chromium"
)

# Create imported target sentry_crashpad::util
add_library(sentry_crashpad::util STATIC IMPORTED)

set_target_properties(sentry_crashpad::util PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>;sentry_crashpad::compat;sentry_crashpad::zlib;sentry_crashpad::mini_chromium;\$<LINK_ONLY:bsm>;-framework CoreFoundation;-framework Foundation;-framework IOKit"
)

# Create imported target sentry_crashpad::mini_chromium
add_library(sentry_crashpad::mini_chromium STATIC IMPORTED)

set_target_properties(sentry_crashpad::mini_chromium PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/crashpad/mini_chromium"
  INTERFACE_LINK_LIBRARIES "-framework ApplicationServices;-framework CoreFoundation;-framework Foundation;-framework IOKit;-framework Security;\$<LINK_ONLY:>"
)

# Create imported target sentry_crashpad::client
add_library(sentry_crashpad::client STATIC IMPORTED)

set_target_properties(sentry_crashpad::client PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/crashpad/client"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>;sentry_crashpad::compat;sentry_crashpad::util;sentry_crashpad::mini_chromium"
)

# Create imported target sentry_crashpad::zlib
add_library(sentry_crashpad::zlib INTERFACE IMPORTED)

set_target_properties(sentry_crashpad::zlib PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ZLIB_CONST;CRASHPAD_ZLIB_SOURCE_SYSTEM"
)

# Create imported target sentry_crashpad::tools
add_library(sentry_crashpad::tools STATIC IMPORTED)

set_target_properties(sentry_crashpad::tools PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>"
)

# Create imported target sentry_crashpad::handler
add_library(sentry_crashpad::handler STATIC IMPORTED)

set_target_properties(sentry_crashpad::handler PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>;sentry_crashpad::compat;sentry_crashpad::minidump;sentry_crashpad::snapshot;sentry_crashpad::util;sentry_crashpad::mini_chromium"
)

# Create imported target sentry_crashpad::crashpad_handler
add_executable(sentry_crashpad::crashpad_handler IMPORTED)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/sentry_crashpad-targets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
